[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; style-src 'self'; script-src 'self' optimize.google.com www.google-analytics.com 'unsafe-hashes'; img-src 'self';"
